name: Test SSH
on: { workflow_dispatch: {} }
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ vars.EC2_HOST }}   # e.g., 54.166.67.96
          username: ubuntu
          key: ${{ vars.EC2_SSH_KEY }}
          script: |
            echo "✅ Connected to $(hostname)"
            whoami && uptime
